### ISSUE TITLE
Anilist authenticator down

### ISSUE THREAD

**Issue by tgsAvylaar** [AzimovParviz/mangadex-anilist-convert#2]
Hi,

Tried running it, and when clicking the authorize button on anilist it redirects me to 
https://thankful-sand-06f5fb203.3.azurestaticapps.net/#access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRjM2FkOTNhYmE3YjM2ZmQ3ODNlNjg5ZTFlZDJiNzdjNjYyOGY4ZDU0Yzg3ZDIzOGU2Zjg3NjQ2MWQ1ZGUyM2ZiYjA1MDcxNzQzODZhMmEwIn0.eyJhdWQiOiIxMDg5MiIsImp0aSI6IjRjM2FkOTNhYmE3YjM2ZmQ3ODNlNjg5ZTFlZDJiNzdjNjYyOGY4ZDU0Yzg3ZDIzOGU2Zjg3NjQ2MWQ1ZGUyM2ZiYjA1MDcxNzQzODZhMmEwIiwiaWF0IjoxNzAzMjc3MjgyLCJuYmYiOjE3MDMyNzcyODIsImV4cCI6MTczNDg5OTY4Miwic3ViIjoiOTM5MzYiLCJzY29wZXMiOltdfQ.f4-KHNf1ZQgVG326xpFbxPnQxCnp5ErPXtlBcsMykq2V5Ko24yEvuAAe7fb2ffIdlXSSLNF2ZnlyUKC50K0L6c15HcPjzMDxUeMMh_f_JQXfwwuBFknmGmCzV8HNdHx95ecO28ToVkMAsJZnd29iuYeNo2GzqavjN8djVEa3QKp7hY13fQDQAkt2tBr2Dj79kosTADq5Afgr7-FDlMsuS3sbg-Cp9G7GCg2RpYEzlhaEuy0b57PJn2XJ1ysRnaGV8MSgi2xbGO9Zez_xlVEpDq424nebZK79sm9GqDch8GS1TePj7anzjavGzjDto0uqtXyy9jyUadYDi33w9VSM3sSRijtL5WME_gN9ecZeUrP6-09SzemGwh0OcD8VpOxoCmE_JaKMZ533-bb22lTCPrKsqlSerdnuo07wjKZQL9A_-IkmW9WxTlSGgP_848sZdPuAHWldXQFV7AmwoWDv4_lxWndDfPz1AwB4sbZS3gtKF2qS94RXxDWxwc_dJCCUV0GYTWJEYX1MN_bP8I87_BQvS4Nejqpbf5dxzIUlUrzul9qFzJBzcJJWfwGasRIokmU6zUFHlXJIN0PZC3kAjVPZdCLH8lU0Nx33GawUiHyxba1N8kEkk2MXm4gCxi-C5Hu74Q_ApTv72euzyAMGzDaH-V6-VLRgEo9doDVbKS8&token_type=Bearer&expires_in=31622400

aka 

![image](https://github.com/AzimovParviz/mangadex-anilist-convert/assets/63151598/060a701a-34c6-4106-b08e-d4bb4ad6dd43)

**Comment by AzimovParviz** [comment]
Yes, sorry about that. I was playing around with Azure hosting and forgot to change the redirect link. I cannot change the redirect url cause I need to reset my password and I used a throwaway email. You can create your own app using these instructions: https://anilist.gitbook.io/anilist-apiv2-docs/overview/oauth/getting-started and then change line 5 in https://github.com/AzimovParviz/mangadex-anilist-convert/blob/master/src/components/LoginWithAnilist/LoginWithAnilist.tsx with your own link. Let me know if you need help

Sorry for the late response, work kept me busy

**Comment by AzimovParviz** [comment]
Well it's been almost a year without any activity so I will close this issue
